### ISSUE TITLE
Configure User-Agent for fetching feeds

### ISSUE THREAD

**Issue by davisagli** [RedTurtle/redturtle.rssservice#10]
We are trying to use this with an RSS feed that needs to be fetched with a specific User-Agent header, not the default from `requests`. Would you accept a PR to configure this via an environment variable or registry setting?

**Comment by cekk** [comment]
Of course..could be a good improvement.
I'm not sure what's the best place to put this change: can the custom header be a problem for other feeds?
In that case probably it could be better to set this header in block settings and not make it global.

What do you think? Anyway, feel free to create a pr about that ;)

**Comment by davisagli** [comment]
Good question. So far I am not aware of a problem with setting a custom User-Agent for other feeds, and I would prefer to avoid adding a new setting that editors might find confusing. So I would add only the (optional, global) environment variable for now, and add the block setting later if it becomes clear it is needed.
